name: bobble_controller_CI

# This determines when this workflow is run
on: [push, pull_request] # on all pushes and PRs

# or more fine-grained
# on:
#   # When master or melodic-devel branch is pushed to
#   push:
#     branches: [ master, melodic-devel ]
#   # When there is a pull request against master
#   pull_request:
#     branches: [ master ]
<<<<<<< HEAD

<<<<<<< HEAD
=======
on: [push, pull_request]
=======
>>>>>>> 9aa543d... Try this action

>>>>>>> 74be9aa... update workflow
jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: melodic, ROS_REPO: testing}
          - {ROS_DISTRO: melodic, ROS_REPO: main}
<<<<<<< HEAD
<<<<<<< HEAD
    env:
      CCACHE_DIR: /github/home/.ccache # Directory for ccache (and how we enable ccache in industrial_ci)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # This step will fetch/store the directory used by ccache before/after the ci run
      - uses: actions/cache@v2
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ matrix.env.ROS_DISTRO }}-${{ matrix.env.ROS_REPO }}
      - name : Install Python Dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install rosbag_pandas matplotlib
      # Run industrial_ci
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{ matrix.env }}
=======
=======
    env:
      CCACHE_DIR: /github/home/.ccache # Directory for ccache (and how we enable ccache in industrial_ci)
>>>>>>> 9aa543d... Try this action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # This step will fetch/store the directory used by ccache before/after the ci run
      - uses: actions/cache@v2
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ matrix.env.ROS_DISTRO }}-${{ matrix.env.ROS_REPO }}
      - name : Install Python Dependencies
        run: python -m pip install --upgrade pip
        pip install rosbag_pandas matplotlib
      # Run industrial_ci
      - uses: 'ros-industrial/industrial_ci@master'
<<<<<<< HEAD
        env: ${{matrix.env}}
>>>>>>> 74be9aa... update workflow
=======
        env: ${{ matrix.env }}
>>>>>>> 9aa543d... Try this action
